# Generated by Django 4.1.5 on 2023-03-15 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_todo_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='author',
        ),
    ]
