# Generated by Django 4.1.5 on 2023-03-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_alter_todo_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_checled',
            field=models.BooleanField(default=False),
        ),
    ]
