# Generated by Django 4.1.5 on 2023-03-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_todo_is_checled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_checled',
            new_name='is_checked',
        ),
    ]
